name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  codeStyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
      
    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v2.0.0
      with:
        skipCommit: false

     
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build project
      run: | 
           cd ./Recipes/app
           gradle build
           
  create Pull Request:
    runs-on: ubuntu-latest
    needs: [codeStyle, build]
    steps:
      - uses: actions/checkout@v2
      - name: Create commits
        run: |
              git config user.name 'BoytsovVA'
              git config user.email 'vladboi8@gmail.com'
              git commit -am "Modify tracked file during workflow"
              git add -A
              git commit -m "Add untracked file during workflow"
      - name: pull request
        uses: peter-evans/create-pull-request@v2
        
