name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  codeStyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
      
    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v2.0.0
      with:
        skipCommit: false

     
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build project
      run: | 
           cd ./Recipes/app
           gradle build
           
  pull-request:
      runs-on: ubuntu-latest
      needs: [build, codeStyle]
      steps:
      - uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.github_token }}
        
